server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
      
dubbo:
  scan:
    basePackages: com.ed
  application:
    name: consumer-sso
  registry:
    address: zookeeper://176.114.11.69:2181?backup=176.114.11.69:2182,176.114.11.69:2183
  